# -*- coding: utf-8 -*-
"""A Network Attack type classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19KglSaCVA-e23D2RSUPcxltPH0xZGla2

#**Karar Ağacı ile KDDC'99 veri seti üzerinde bir Ağ Saldırı türü sınıflandırma**

**DİLAVER ŞAHİN**

**No:215509031**

**Makina Öğrenmesi methodu olan Karar ağacı **

> KDD Cup 1999 veri kümesi: Veri kümesi, askeri bir bilgisayar ağının simülasyonudur; kayıtlar, normal bağlantılar veya tespit edilen izinsiz giriş (belirli bir saldırı türüyle) olarak sınıflandırılan internet bağlantılarından oluşur.

Veri setini buradan çektim:
http://kdd.ics.uci.edu/databases/kddcup99/kddcup99.html

# Gerekli kütüphaneleri colabda var olsa da güncellerini indirmesi için çalıştırıyorum.
"""

# Gerekli kütüphaneleri yükleyin
!pip install scikit-learn pandas matplotlib seaborn --quiet

"""# Gerekli kütüphaneleri yükleyelim"""

# Gerekli kütüphaneleri yükleyin
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from google.colab import drive

"""#Drive colaba bağlayarak veri setimizi alıyoruz"""

# Google drive mount ederek veri setini alma
from google.colab import drive
drive.mount('/content/drive')

"""# ***Sütun Türlerini ve csv foramtındaki data setimizi yüklüyoruz: ***
Veri kümesinin 42 farklı sütun bulunmaktadır ve bu sütunlar aşağıda verilmiştir. Sütunlar, kodlanması gereken kategorik verileri veya normalleştirilmesi gereken sürekli değerleri tanımlayabilir.

data değişkenimzin tanımlı olup olmadığını kontrol ediyoruz.
"""

import pandas as pd
# CSV formatındaki veri setini yükleyin
file_path = '/content/drive/My Drive/kddcup.data.corrected'  # Dosyanızın yolu
columns = ["duration", "protocol_type", "service", "flag", "src_bytes", "dst_bytes", "land",
           "wrong_fragment", "urgent", "hot", "num_failed_logins", "logged_in", "num_compromised",
           "root_shell", "su_attempted", "num_root", "num_file_creations", "num_shells",
           "num_access_files", "num_outbound_cmds", "is_host_login", "is_guest_login",
           "count", "srv_count", "serror_rate", "srv_serror_rate", "rerror_rate",
           "srv_rerror_rate", "same_srv_rate", "diff_srv_rate", "srv_diff_host_rate",
           "dst_host_count", "dst_host_srv_count", "dst_host_same_srv_rate", "dst_host_diff_srv_rate",
           "dst_host_same_src_port_rate", "dst_host_srv_diff_host_rate", "dst_host_serror_rate",
           "dst_host_srv_serror_rate", "dst_host_rerror_rate", "dst_host_srv_rerror_rate", "attack",
           "last_flag"]

data = pd.read_csv(file_path, header=None, names=columns)
data.head()

pd.set_option('display.max_rows', 10)

if 'data' in globals():
    print("data değişkeni tanımlı.")
else:
    print("data değişkeni tanımlı değil.")

"""# **Veriyi keşfetmek ve eksik değerleri kontrol etmek**

Verilerimzin doğru çıkıp çıkmadığını kontrol edip sutun ve rowların düzgünce parse edildiğini kontrol ediyoruz.
"""

# Veri keşfi
print("Veri Seti Boyutları:", data.shape)
print("Eksik Değerler:\n", data.isnull().sum())

# Saldırı türlerine göre dağılım
print("\nSaldırı Türleri Dağılımı:\n", data['attack'].value_counts())

# Özet istatistikler
data.describe()



"""# **Saldırı türlerine göre dağılımı tablolaştırıyoruz.**

Smurf atağının DDOS türü olab bir atak bunun çoğunlukla olduğunu görüyoruz.
"""

# Saldırı türlerine göre dağılımı görselleştirme
plt.figure(figsize=(12, 6))
sns.countplot(data=data, x='attack', order=data['attack'].value_counts().index)
plt.title("Saldırı Türlerine Göre Dağılım")
plt.xlabel("Saldırı Türü")
plt.ylabel("Frekans")
plt.xticks(rotation=90)
plt.show()

"""# **Veri setiğimizdeki atak türlerini listeliyoruz.**"""

print(data['attack'].unique())

"""# **Sınıflandırmada kullanacağımzı atak türlerini haritasını çıkarıp kontrolünü yapıyoruz.**"""

# İkili sınıflandırma hedef değişkeni
data['binary_label'] = data['attack'].apply(lambda x: 0 if x == "normal" else 1)

# Çoklu sınıflandırma hedef değişkeni
attack_mapping = {
    "normal.": "normal",  # Normal traffic
    "neptune.": "dos",    # DoS attack
    "smurf.": "dos",      # DoS attack
    "teardrop.": "dos",   # DoS attack
    "land.": "dos",       # DoS attack
    "back.": "dos",       # DoS attack (added based on context)
    "pod.": "dos",        # DoS attack (added based on context)
    "satan.": "probe",    # Probing/scanning attack
    "ipsweep.": "probe",  # Probing/scanning attack
    "portsweep.": "probe",# Probing/scanning attack
    "nmap.": "probe",     # Probing/scanning attack
    "guess_passwd.": "r2l",  # Remote-to-local attack
    "ftp_write.": "r2l",     # Remote-to-local attack
    "imap.": "r2l",          # Remote-to-local attack
    "phf.": "r2l",           # Remote-to-local attack
    "multihop.": "r2l",      # Remote-to-local attack
    "warezmaster.": "r2l",   # Remote-to-local attack
    "warezclient.": "r2l",   # Remote-to-local attack
    "spy.": "r2l",           # Remote-to-local attack
    "buffer_overflow.": "u2r",  # User-to-root attack
    "loadmodule.": "u2r",       # User-to-root attack
    "perl.": "u2r",             # User-to-root attack
    "rootkit.": "u2r",          # User-to-root attack
}
data['multi_label'] = data['attack'].map(attack_mapping)

# Sonuçları kontrol et
print("İkili Sınıflandırma Etiketleri:\n", data['binary_label'].value_counts())
print("\nÇoklu Sınıflandırma Etiketleri:\n", data['multi_label'].value_counts())

"""# **Attack değerleinin eksik olduğu alanları normal ile dolduruyor**"""

print(data['attack'].isnull().sum())  # Eksik değerleri kontrol et
data['attack'] = data['attack'].fillna("normal")  # Eksik değerleri "normal" ile doldur

if 'data' in globals():
    print("data değişkeni tanımlı.")
else:
    print("data değişkeni tanımlı değil.")

"""# **Kategorik Değişkenlerin Kodlanması**
**Amaç:** Kategorik değişkenleri (protocol_type, service, flag) sayısal formatlara dönüştürmek.

**Yöntem:** pd.get_dummies fonksiyonu ile her kategorik değişken için "sıcak kodlama" (one-hot encoding) uygulanır.

Örneğin, protocol_type değişkeninde tcp, udp, icmp kategorileri varsa, bu işlem protocol_type_tcp, protocol_type_udp gibi sütunlar oluşturur.
drop_first=True: Fazladan bir kategoriyi (referans olarak) düşürür, bu da multikolineariteyi azaltır.

**Gereksiz Sütunların Çıkarılması:**
amaç: Model eğitimi için kullanılmayacak veya hedef değişken olarak tanımlanan sütunları çıkararak özellikler (X) oluşturmak.
"""

import pandas as pd
# Kategorik değişkenleri kodlama
data_encoded = pd.get_dummies(data, columns=["protocol_type", "service", "flag"], drop_first=True)

# Özelliklerden gereksiz sütunları çıkar
X = data_encoded.drop(['attack', 'binary_label', 'multi_label'], axis=1)

# İkili sınıflandırma için hedef değişken
y_binary = data['binary_label']

# Çoklu sınıflandırma için hedef değişken
y_multi = data['multi_label']

"""Değişken tanımlımı kontrolü"""

if 'X' in globals():
    print("X değişkeni tanımlı.")
else:
    print("X değişkeni tanımlı değil.")

if 'y_binary' in globals():
    print("y_binary değişkeni tanımlı.")
else:
    print("y_binary değişkeni tanımlı değil.")

if 'y_multi' in globals():
    print("y_multi değişkeni tanımlı.")
else:
    print("y_multi değişkeni tanımlı değil.")

"""#**İkili Sınıflandırma modeli eğitimi**

**Amaç:** Veri setini ikiye ayırmak: Eğitim ve test.

**Parametreler:**

**X:** Özellikler (bağımsız değişkenler).

**y_binary**: Hedef değişken (bağımlı değişken, 0: normal, 1: saldırı).

**test_size=0.5**: Verinin %50'si test, %50'si eğitim için ayrılır.

**random_state=42**: Aynı rastgele ayrımın tekrar yapılabilmesi için sabit bir değer.
"""

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

# Eğitim ve test verisi
X_train, X_test, y_train, y_test = train_test_split(X, y_binary, test_size=0.5, random_state=42)

# Random Forest Modeli
rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)

# Tahmin
y_pred = rf_model.predict(X_test)

# Performans değerlendirme
print("İkili Sınıflandırma Sonuçları:\n", classification_report(y_test, y_pred))

if 'data' in globals():
    print("data değişkeni tanımlı.")
else:
    print("data değişkeni tanımlı değil.")

"""#Çoklu sınıflandırma modeli eğitimi:

Amaç: Veri setini eğitim ve test veri setlerine bölmek.

**X:** Özellikler (bağımsız değişkenler). Bu, saldırının özelliklerini (örneğin, duration, protocol_type) içerir.

**y_multi:** Hedef değişken (etiketler).

**Parametreler:**

**test_size=0.5:** Veri setinin %50'u test verisi olarak ayrılır.

**random_state=42:** Veri ayrımının tekrarlanabilir olmasını sağlar.

**Sonuç:**

**_train ve y_train:** Modeli eğitmek için kullanılan veri.

**X_test ve y_test:** Modelin doğruluğunu test etmek için kullanılan veri.
"""

# Hedef Değişken
y_multi = data["multi_label"]

# Eğitim ve Test Verisi
X_train, X_test, y_train, y_test = train_test_split(X, y_multi, test_size=0.5, random_state=42)

# Model Eğitimi
rf_multi_model = RandomForestClassifier()
rf_multi_model.fit(X_train, y_train)

# Tahmin ve Değerlendirme
y_multi_pred = rf_multi_model.predict(X_test)
print(classification_report(y_test, y_multi_pred))

"""# Saldırı türlerine göre dağılımın grafiği


"""

import matplotlib.pyplot as plt
import seaborn as sns

# Daha güzel ve anlaşılır bir görselleştirme için stil ve renk paletini değiştirebiliriz
plt.figure(figsize=(10,6))
sns.set(style="whitegrid")  # Beyaz grid arka plan

# Saldırı türlerine göre dağılım
ax = sns.countplot(data=data, x="multi_label", order=data['multi_label'].value_counts().index)

# Başlık, etiketler ve estetik düzenlemeler
plt.title("Saldırı Türlerine Göre Dağılım", fontsize=16, weight='bold')
plt.xlabel("Saldırı Türü", fontsize=12)
plt.ylabel("Frekans", fontsize=12)

# X eksenindeki etiketleri döndürme (yazılar kesilmesin diye)
plt.xticks(rotation=45, ha='right')

# Her çubuğun üstüne frekans değeri eklemek
for p in ax.patches:
    ax.annotate(f'{p.get_height()}', (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='center', fontsize=12, color='black', xytext=(0, 5),
                textcoords='offset points')

# Grafiği gösterme
plt.tight_layout()  # Grafik sıkışmasın diye düzenleme yapar
plt.show()